# -*- coding: utf-8 -*-
"""Altair Data Science Hackathon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pzz4u9WqiUEiealwjp-YQ1e3Pba9cqld
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for the plots
sns.set(style="whitegrid")

# Load the dataset
df = pd.read_csv('/content/Sleep_health_and_lifestyle_dataset.csv')

# Display the first few rows of the dataset
df.head()

# Summary statistics of the dataset
df.describe()

# Check for missing values
missing_values = df.isnull().sum()
print(missing_values)

# Correlation matrix
plt.figure(figsize=(10, 8))
# Select only numerical columns for correlation calculation
numerical_df = df.select_dtypes(include=['float', 'int'])
sns.heatmap(numerical_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

# Histograms for numerical columns
df.hist(figsize=(15, 10), bins=20, color='blue', edgecolor='black')
plt.suptitle('Histograms of Numerical Columns')
plt.show()

# Box plots to check for outliers
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, palette='pastel')
plt.title('Box Plots for Numerical Columns')
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Sleep Duration', y='Stress Level', data=df)
plt.title('Scatter Plot of SleepDuration vs StressLevel')
plt.show()

print(df.columns)  # Print the names of all columns in the DataFrame

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Age', y='Sleep Duration', data=df)
plt.title('Scatter Plot of Age vs SleepDuration')
plt.show()

# Bar plot for a categorical variable
plt.figure(figsize=(8, 6))
sns.countplot(x='BMI Category', data=df, palette='muted')
plt.title('Distribution of CategoricalVariable')
plt.show()